services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: appcore
      POSTGRES_USER: appcore
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  console:
    image: hasura/graphql-engine:v2.40.2-ce.cli-migrations-v3.ubi
    restart: always
    ports:
      - "1695:1695"
      - "1693:1693"
    depends_on:
      graphql:
        condition: service_healthy
    volumes:
      - type: bind
        source: ./
        target: /app
        read_only: false
    working_dir: /app
#command: hasura-cli console --no-browser --address 0.0.0.0 --api-port 1693 --console-port 1695 --endpoint http://graphql:8080 --console-hge-endpoint http://${DEVELOPMENT_DOMAIN:-localhost}:8080
    entrypoint: hasura-cli console --no-browser --address 0.0.0.0 --api-port 1693 --console-port 1695 --endpoint http://graphql:8080 --console-hge-endpoint http://${DEVELOPMENT_DOMAIN:-localhost}:8080
    environment:
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgres://appcore:${POSTGRES_PASSWORD}@postgres:5432/appcore"
      HASURA_GRAPHQL_METADATA_DIR: "/app/metadata"
      HASURA_GRAPHQL_MIGRATION_DIR: ""
    healthcheck:
      test:
          - CMD-SHELL
          - timeout 1s bash -c ':> /dev/tcp/127.0.0.1/1695' || exit 1
      timeout: 60s
      interval: 5s
      start_period: 500s
  graphql:
    image: hasura/graphql-engine:v2.40.2-ce.ubi
    restart: always
    ports:
      - "8080:8080"
    environment:
      APPCORE_DATABASE_URL: "postgres://appcore:${POSTGRES_PASSWORD}@postgres:5432/appcore"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgres://appcore:${POSTGRES_PASSWORD}@postgres:5432/appcore"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "false"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup, http-log, webhook-log, websocket-log, query-log"
      HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
      HASURA_GRAPHQL_DEFAULT_NAMING_CONVENTION: "hasura-default"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "annonymous"
    healthcheck:
      test:
        - CMD-SHELL
        - curl http://localhost:8080/healthz > /dev/null 2>&1
      timeout: 60s
      interval: 5s
      start_period: 60s
volumes:
  postgres_data: {}
