#!/bin/bash

RUNCORE_URL="https://raw.githubusercontent.com/creatiiv-io/runcore/main/runcore"
DOCKER_VERSION=$(docker --version 2>/dev/null)
GIT_VERSION=$(git --version 2>/dev/null)
WGET_INSTALL=$(wget --version 2>/dev/null | head -n1)
INSTALL_DIR=${1%/*}
INSTALL_DIR=${INSTALL_DIR:-/usr/local/bin/}
INSTALL_NAME=${1##*/}
INSTALL_NAME=${INSTALL_NAME:-runcore}

# also uses sed, grep, ls and find

# check for runcore
if command -v runcore &> /dev/null; then
    read -p "Runcore is already installed do you want to upgrade? (Y/n): " upgrade
    upgrade=${upgrade:-Y}  # Default to "Y" if no input is given
    if [ "$upgrade" = "y" ] || [ "$upgrade" = "Y" ]; then
      sudo rm -f "$INSTALL_DIR$INSTALL_NAME"
    else
      echo "Aborting instaliation."
      exit 1
    fi
fi

# check for docker
[ -z "DOCKER_VERSION" ] && echo "docker is not installed" && exit 1

#check for git
[ -z "GIT_VERSION" ] && echo "git is not installed" && exit 1

#check for wget
[ -z "WGET_VERSION" ] && echo "wget is not installed" && exit 1

dev_mode="$(grep "RUNCORE_URL" $PWD/runcore 2>/dev/null)"

if [ -z "$dev_mode" ]; then
  sudo wget -qO "$INSTALL_DIR$INSTALL_NAME" "$RUNCORE_URL"
  sudo chmod +x "$INSTALL_DIR$INSTALL_NAME"
else
  sudo ln -s $PWD/runcore "$INSTALL_DIR$INSTALL_NAME"
fi

# Check the exit status
if [ $? -eq 0 ]; then
  echo "CONGRADULATIONS! - YOU DID IT!!!"
  echo "runcore installed in $INSTALL_DIR$INSTALL_NAME"
  [ -n "$dev_mode" ] && echo "this is linked for development mode"
  echo ""
  echo "  To get started you should try:"
  echo ""
  echo "  $INSTALL_NAME init"
  echo "  $INSTALL_NAME dev"
  echo "  $INSTALL_NAME tutorial"
  echo ""
else
  echo "Failed to download runcore cli at $INSTALL_DIR$INSTALL_NAME"
fi
