#!/bin/bash

RUNCORE_URL="https://raw.githubusercontent.com/creatiiv-io/runcore/main/runcore"

DOCKER_VERSION=$(docker --version 2>/dev/null)
GIT_VERSION=$(git --version 2>/dev/null)
WGET_VERSION=$(wget --version 2>/dev/null | head -n1)

DIRNAME=${1%/*}
DIRNAME=${DIRNAME:-/usr/local/bin}
RUNNAME=${1##*/}
RUNNAME=${RUNNAME:-runcore}
COMPDIR="/usr/share/bash-completion/completions"

# also uses sed, grep, ls, find, env, tee

# ask a question
function confirm() {
    read -n 1 -p "$1 (Y/n): " -r
    echo
    [[ $REPLY =~ ^[Yy]?$ ]]
}

# setup tab completion
function setup_completion() {
  [ -d "$COMPDIR" ] && sudo tee "${COMPDIR}/${RUNNAME}" > eval <<EOF
#!/bin/bash

complete -C "${RUNNAME} $'\t'" ${RUNNAME}
EOF
}

# check for runcore
if command -v runcore &> /dev/null; then
  if confirm "Runcore is already installed do you want to reinstall?"; then
    sudo rm -f "${DIRNAME}/${RUNNAME}"
  else
    echo "Aborting instaliation."
    exit 1
  fi
fi

# check for docker
[ -z "DOCKER_VERSION" ] && echo "docker is not installed" && exit 1

# check for git
[ -z "GIT_VERSION" ] && echo "git is not installed" && exit 1

# check for wget
[ -z "WGET_VERSION" ] && echo "wget is not installed" && exit 1

# check for dev mode
dev_mode="$(grep "RUNCORE" "${PWD}/runcore" 2>/dev/null)"
if [ -z "${dev_mode:+x}" ]; then
  sudo wget -qO "${DIRNAME}/${RUNNAME}" "${RUNCORE_URL}"
  sudo chmod +x "${DIRNAME}/${RUNNAME}"
else
  sudo ln -s ${PWD}/runcore "${DIRNAME}/${RUNNAME}"
fi

# Check the exit status
if [ $? = 0 ]; then
  setup_completion

  echo "CONGRADULATIONS! - YOU DID IT!!!"
  echo "runcore installed in ${DIRNAME}/${RUNNAME}"
  [ -n "${dev_mode:+x}" ] && echo "this is linked for development mode"
  echo ""
  echo "  To get started you should try:"
  echo ""
  echo "  ${RUNNAME} init"
  echo "  ${RUNNAME} dev"
  echo "  ${RUNNAME} tutorial"
  echo ""
else
  echo "Failed to download runcore cli at ${DIRNAME}/${RUNNAME}"
fi
