#!/bin/bash

export RUNNAME="${0##*/}"
export GITROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
export RUNCORE="$GITROOT/.runcore"
export INSTALL="http://github.com/creatiiv-io/runcore"
export DEVELOP=$(grep "RUNCORE" "$GITROOT/runcore" 2>/dev/null)
export ENVROOT="$(cd "$GITROOT"; basename "$PWD")"

[ -n "${DEVELOP:+x}" ] && export RUNCORE="$GITROOT"

export ACTIONS="$RUNCORE/system/actions"

# cleanroom environment
function cleanroom() {
  {
    [ -f "$RUNCORE/system/default.env" ] && cat "$RUNCORE/system/default.env" | sed 's/^/export /'
    [ -f "$RUNCORE/.config" ] && toenvfromconfig "$RUNCORE/.config" | sed 's/^/export /'
    [ -f "$RUNCORE/system/require.env" ] && cat "$RUNCORE/system/require.env" | sed 's/^/export /'
    echo RUNCORE='"'$RUNCORE'"' | sed 's/^/export /'
    echo GITROOT='"'$GITROOT'"' | sed 's/^/export /'
    echo ENVROOT='"'$ENVROOT'"' | sed 's/^/export /'
    echo cd '"'$GITROOT'"'
    echo $@
  } | env -i bash
}

# confirm something
function confirm() {
  read -n 1 -p "$1 (Y/n): " -r
  echo
  [[ $REPLY =~ ^[Yy]?$ ]]
}

# tab completion
function completion(){
  local words=()

  IFS=' ' read -r -a words <<< "$COMP_LINE"
  [[ "$COMP_LINE" == *' ' ]] && words+=("")

  [ -z "${COMP_LINE:+x}" ] && words=( "$RUNNAME" "$@" )

  local count=${#words[@]}
  local action="${words[1]}"
  local subact=( "${words[@]:2}" )

  case "$action" in
    init|version|tutorial)
      return
      ;;
    help)
      if [[ $count < 4 ]]; then
        compgen -W "init $(ls "$ACTIONS" 2>/dev/null)" -- "$subact"
        return
      else
        action="$subact"
        subact=( help "${subact[@]:2}" )
      fi
      ;;
    *)
      if [[ $count < 3 ]]; then
        compgen -W "init help tutorial version $(ls "$ACTIONS" 2>/dev/null)" -- "$action"
        return
      fi
  esac

  [ -f "$ACTIONS/$action" ] && source "$ACTIONS/$action" $'\t' "$action" "${subact[@]}"
}

# run docker containers
function containers() {
  # setup config
  serveconfig

  # are we doing a custom or an internal yaml
  if [ -f "$GITROOT/docker-compose.yaml" ]; then
    cleanroom docker compose -f "$GITROOT/docker-compose.yaml" "${@:2}"
  else
    cleanroom docker compose -f "$RUNCORE/system/$1.yaml" "${@:2}"
  fi
}

# delegate to extensions
function delegate() {
  if [ -f "$ACTIONS/$1" ]; then
    source "$ACTIONS/$1" "$@"
  else
    help "$@"
  fi
}

# execute inside docker
function dockerexec() {
  docker exec -it "$ENVROOT-$1-1" "${@:2}"
}

# find extension actions
function extensions() {
  [ ! -d "$ACTIONS" ] && echo "no actions $ACTIONS" && return

  for extscript in $ACTIONS/*; do
    $extscript "$@"
  done
}

# check if files match
function filematch() {
  [ "$(md5sum "$1" | sed "s/ .*//")" = "$(md5sum "$2" | sed "s/ .*//")" ]
}

# display help
function help() {
  case $1 in
    init)
      echo "initialize the current directory or one passed with runcore"
      ;;
    version)
      echo "version number will either show the base CLI version or the specific version of runcore for your directory"
      ;;
    tutorial)
      echo "learn all the features in a step by step totorial"
      ;;
    *)
      # if we have an extension script run it 
      [ -f "$ACTIONS/$2" ] && source $ACTIONS/$2 $@

      # show the defualt help menu
      echo "RUNCORE DEVELOPER CLI - $(version)"
      echo "AI + Hasura + LiveKit + IPFS + Steroids"
      echo "©2024 Creatiiv Artists LLC - Apache-2.0"
      echo ""
      echo "Commands:"
      echo ""
      echo "  $RUNNAME init"
      echo "  $RUNNAME version"
      echo ""
 
      # show extension
      extensions help

      echo ""
      echo "Help:"
      echo ""
      echo "  $RUNNAME help [command]"
      echo "  $RUNNAME tutorial"
      ;;
  esac
}

# initialize repo
function init() {
  if [ -n "$1" ]; then
    mkdir -p "$1"
    cd "$1"
    exec "$RUNNAME" init
  fi

  # check if we are not in a git repository
  if [ -z "$GITROOT" ]; then
    if confirm "You are not in a repo. Run git init?"; then
      git init &>/dev/null
      GITROOT="."
      RUNCORE="./.runcore"
    else
      echo "Initialization aborted."
      exit 1
    fi
  fi

  # if we are in the runcore repo show error
  [ -n "${DEVELOP:+x}" ] && echo "cannot initialize in runcore source directory" && exit 1

  #install runcore submodule
  (
    cd "$GITROOT"
    git submodule add "$INSTALL" ".runcore"
  ) &>/dev/null

  # copy all core files
  verifycopy "$RUNCORE/core/" "$GITROOT/core/"
  verifycopy "$RUNCORE/public/" "$GITROOT/public/"

  local is_old="$(ls "$RUNCORE" 2>/dev/null)"

  echo "$RUNNAME ${is_old:+re}installed - YAY!!!"

  extensions init

  echo ""
  echo "Don't forget to commit changes:"
  echo ""
  echo "  git add *"
  echo "  git commit -m '$RUNNAME ${is_old:+re}installed'"
}

# display tutorial
function tutorial() {
  xdg-open https://runcore.dev/tutorial
}

# serve configuration
function saveconfig() {
  local config="$1"

  # save new setting first
  [ -n "$3" ] && echo "$2=$3" | toconfigfromenv >> "$config"

  # reorder and generate config
  {
    echo "setting:configuration"
    cleanroom env | sed -E '/^(#|$)/d; /^(SETTING|SHLVL|PWD|OLDPWD|_)=/d' | sort | toconfigfromenv
  } > "${config##*/}"

  mv "${config##*/}" "$config"
}

# serve configuration
function serveconfig() {
  # get current config
  local config=$(readlink "$RUNCORE/.config")

  # are we trying to change it
  [ -n "$1" ] && config="$1"

  # make sure we have a filename
  config="${config:-local}"
  config="$GITROOT/core/config/conf.${config##*.}"

  # fill conf file if it doesn't exist
  [ ! -f "$config" ] && saveconfig "$config"

  # remove old config if we are replacing
  [ -n "$1" ] && rm -f "$RUNCORE/.config"

  # link the config if needed
  [ ! -f "$RUNCORE/.config" ] && ln -s "$config" "$RUNCORE/.config"
}

# convert env to config format
function toconfigfromenv() {
  while IFS='=' read -r key value; do
    echo "$(echo "$key" | tr 'A-Z' 'a-z' | sed -E 's/[^a-z0-9]+/./g'):$value"
  done < "${1:-/dev/stdin}"
}

# convert config to env format
function toenvfromconfig() {
  while IFS=':' read -r key value; do
    echo "$(echo "$key" | tr 'a-z' 'A-Z' | sed -E 's/[^A-Z0-9]+/_/g')=$value"
  done < "${1:-/dev/stdin}"
}

# display version
function version() {
  # if not in git return
  [ ! -d "$RUNCORE/.git" ] && echo "v1.2-cli" && return

  # git tag
  git_tag=$(cd $RUNCORE; git describe --tags --exact-match 2>/dev/null)

  # show git version
  echo "${git_tag:-vBeta}-$(cd $RUNCORE; git rev-parse --short HEAD)"
}

# verify each file as you copy
function verifycopy() {
  # loop through files
  for file in $(find "$1" -type f); do
    local dest="$2/${file#$1}"

    mkdir -p "${dest%/*}"

    [ ! -e "$dest" ] || filematch "$dest" "$file" || confirm "Replace /core/${dir##*/}/${file##*/}?" && cp "$file" "$dest"
  done
}

# switch for base version
case $1 in
  $'\t') completion "${@:2}";;
  version) version;;
  init) init "$2";;
  tutorial) tutorial "$@";;
  help) help "${@:2}";;
  *) delegate "$@";;
esac
