table:
  name: configs
  schema: client
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
  - name: form
    using:
      foreign_key_constraint_on: form_id
select_permissions:
  - role: agent
    permission:
      columns:
        - account_id
        - data
        - form_id
      filter:
        account:
          users:
            user_id:
              _eq: X-Hasura-User-Id
    comment: ""
  - role: owner
    permission:
      columns:
        - account_id
        - data
        - form_id
      filter:
        account:
          users:
            user_id:
              _eq: X-Hasura-User-Id
    comment: ""
