table:
  name: settings
  schema: client
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
  - name: default
    using:
      foreign_key_constraint_on: setting_id
