#!/bin/bash

# bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  if [ "$action" = config ] && [ -z "$subact" ]; then
    compgen -W "core.environment $(sed '1d; s/:.*$//' "$RUNCORE/.config")" -- "$subact"
  fi
}

# display help
function help() {
  case $1 in
    config)
      echo "start a local dev environment"
      ;;
    *)
      echo "  $RUNNAME config"
      ;;
  esac
}

# set config
function config() {
  local config=$(readlink "$RUNCORE/.config")
  local name=${1,,} 

  # fill config with variable
  config=$(saveconfig "$config" "$@")

  # show docker environent
  if [ "$1" = "core.environment" ]; then
    cleanroom env | sed -E '/^(#|$)/d; /^(SETTING|SHLVL|PWD|OLDPWD|_)=/d' | sort
  # show full config
  elif [ -z "$1" ]; then
    echo "setting:configuration"
    {
      cleanroom env
      echo 'CORE_ENVIRONMENT=$(env)'
    } | sed -E '/^(#|$)/d; /^(SETTING|SHLVL|PWD|OLDPWD|_)=/d' | toconfigfromenv | sort
  # show single config
  elif [ -z "$2" ]; then
    cleanroom env | sed -E '/^(#|$)/d; /^(SETTING|SHLVL|PWD|OLDPWD|_)=/d' | toconfigfromenv | grep "^$name"
  fi
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  config) config "${@:2}";;
esac
