#!/usr/bin/env bash

# bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  if [ "$action" = env ] && [ "${#subact[@]}" = 1 ]; then
    compgen -W "$(ls "${GITROOT}/core/config")" -- "$subact"
  fi
}

# display help
function help() {
  case $1 in
    config)
      echo "start a local dev environment"
      ;;
    *)
      echo "  $RUNNAME config"
      ;;
  esac
}

# config settings
function config() {
  local config="${GITROOT}/core/config/${1}"
  local action="${@:2}"
  local rtn

  # make sure we have a valid config file
  [ ! -f "$config" ] && echo "Not a valid config." && return

  local tempfile="$(mktemp "/tmp/runcore.XXXXXX")"

  # if we have an action
  if [ -n "$action" ]; then
    # make sure the action is vailid
    [[ ! "$action" =~ ^[+-]([^:]+:?)+$ ]] && echo "Invalid action." && return

    # add line to file
    echo "$action" >> "$config"
  fi

  # run dataload and send output to tempfile
  runexec postgres pg_dataload "$1" 2> >(sed '1d' >&2) 1>"$tempfile"

  rtn=$?

  # copy tempfile if we didn't have errors
  [ "$?" = 0 ] && cat "$tempfile" > "$config"

  # remove tempfile
  rm -rf "$tempfile"

  # return config
  cat "$config"
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  config) config "${@:2}";;
esac
