#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    console)
      echo "start a local console"
      ;;
    *)
      echo "  $RUNNAME console"
      ;;
  esac
}

# run something
case $1 in
  help) help ${@:2};;
  console) console ${@:2};;
esac
