#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    console)
      echo "start a local console"
      ;;
    *)
      echo "  $RUNNAME console"
      ;;
  esac
}

# open console
function console() {
  local url=""

  runexec -it hasura bash -c '
    echo "version: 3" > config.yaml

    hasura-cli console \
    --no-browser \
    --address ${RUNCORE_CONSOLE_DOMAIN} \
    --api-port 80 \
    --api-host http://${RUNCORE_CONSOLE_DOMAIN} \
    --console-port 9695 \
    --endpoint http://hasura:8080 \
    --static-dir /srv/console-assets \
    --console-hge-endpoint http://${RUNCORE_CONSOLE_DOMAIN}
  ' | while IFS= read -r line; do
    if [ -z "$url" ]; then
      url=$(echo "$line" | sed -n 's/^.*\(http:\/\/[^:]*\).*$/\1/p')

      [ -n "$url" ] && echo -e "Opening Console: $url/console"
      [ -n "$url" ] && xdg-open "$url/console"
      [ -z "$url" ] && echo "$line"
    fi
  done
}

# run something
case $1 in
  help) help ${@:2};;
  console) console ${@:2};;
esac
