#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    console)
      echo "start a local console"
      ;;
    *)
      echo "  $RUNNAME console"
      ;;
  esac
}

function console() {
  runexec hasura bash -c '
    echo "version: 3" > config.yaml

    hasura-cli console \
    --no-browser \
    --address ${RUNCORE_CONSOLE_DOMAIN} \
    --api-port 80 \
    --api-host http://${RUNCORE_CONSOLE_DOMAIN} \
    --console-port 9695 \
    --endpoint http://hasura:8080 \
    --static-dir /srv/console-assets \
    --console-hge-endpoint http://${RUNCORE_CONSOLE_DOMAIN}
  ' | while IFS= read -r line; do
    url=$(echo "$line" | sed -n 's/^.*\(http:\/\/[^:]*\).*$/\1/p')

    if [ -n "$url" ]; then
      echo "Opening Console: $url/console"
      xdg-open "$url/console"
    fi
  done
}

# run something
case $1 in
  help) help ${@:2};;
  console) console ${@:2};;
esac
