#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    custom)
      echo "Customize Docker and Caddy files"
      ;;
    *)
      echo "  $RUNNAME custom*"
      ;;
  esac
}

function custom() {
  # make sure we are not dev
  [ -n "${DEVCORE:+x}" ] && echo "You cannot instanciate runcore custom in development repo." && return

  runcompose config --services | sed -E '1i services:; s/^(.*)$/  \1:/' > "${RUNCORE}/.docker"

  # copy files
  verifycopyfile "$RUNCORE/.docker" "$GITROOT/docker-compose.yaml"
  verifycopyfile "$RUNCORE/system/Caddyfile" "$GITROOT/Caddyfile"

  rm -f "${RUNCORE}/.docker"
}

# run something
case $1 in
  help) help "${@:2}";;
  custom) custom;;
esac
