#!/bin/bash

# display help
function help() {
  case $1 in
    custom)
      echo "Customize Docker and Caddy files"
      ;;
    *)
      echo "  $RUNNAME custom"
      ;;
  esac
}

function custom() {
  verifycopy "$RUNCORE/system/development.yaml" "$GITROOT/docker-compose.yaml"
  verifycopy "$RUNCORE/system/Caddyfile" "$GITROOT/Caddyfile"
}

# run something
case $1 in
  help) help "${@:2}";;
  custom) custom;;
esac
