#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    custom)
      echo "Customize Docker and Caddy files"
      ;;
    *)
      echo "  $RUNNAME custom"
      ;;
  esac
}

function custom() {
  # make sure we are not dev
  [ -n "${DEVCORE:+x}" ] && echo "You cannot instanciate runcore custom in development repo." && return

  # copy files
  verifycopyfile "$RUNCORE/system/development.yaml" "$GITROOT/docker-compose.yaml"
  verifycopyfile "$RUNCORE/system/Caddyfile" "$GITROOT/Caddyfile"
}

# run something
case $1 in
  help) help "${@:2}";;
  custom) custom;;
esac
