#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    deploy)
      echo "deploy a production environment"
      ;;
    *)
      echo "  $RUNNAME deploy*"
      ;;
  esac
}

# run something
case $1 in
  help) help ${@:2};;
  deploy) deploy ${@:2};;
esac
