#!/bin/bash

#bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  case "$action" in
    help)
      echo down
      ;;
    down) 
      compgen -W "$(containers development config --services)" -- "$subact"
      ;;
  esac
}

# display help
function help() {
  case $1 in
    down)
      echo "stop container environment"
      ;;
    *)
      echo "  $RUNNAME down"
      ;;
  esac
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  down) containers development down "${@:2}";;
esac
