#!/bin/bash

#bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  if [ "$action" = down ] && [ "${#subact[@]}" = 1 ]; then
    compgen -W "$({
      runcompose development config --services
      runcompose production config --services
    } | uniq)" -- "$subact"
  fi
}

# display help
function help() {
  case $1 in
    down)
      echo "stop container environment"
      ;;
    *)
      echo "  $RUNNAME down"
      ;;
  esac
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  down) runcompose development down "${@:2}";;
esac
