#!/usr/bin/env bash

#bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  if [ "$action" = exec ] && [ "${#subact[@]}" = 1 ]; then
    compgen -W "$(runcompose config --services)" -- "$subact"
  fi
}

# display help
function help() {
  case $1 in
    exec)
      echo "execue commandline in the container environment"
      ;;
    *)
      echo "  $RUNNAME exec"
      ;;
  esac
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  exec) runexec "${@:2}";;
esac
