#!/usr/bin/env bash

# bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  if [ "$action" = log ] && [ "${#subact[@]}" = 1 ]; then
    compgen -W "$(runcompose development config --services)" -- "$subact"
  fi
}

# display help
function help() {
  case $1 in
    log)
      echo "show logs for docker container"
      ;;
    *)
      echo "  $RUNNAME log"
      ;;
  esac
}

# display docker logs
function logs() {
  [ -z "$1" ] && echo "Usage:

  $RUNNAME logs [service]" && return

  cleanroom docker logs \${CORE_RUNNAME}-$1-1 "${@:2}"
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  logs) logs "${@:2}";;
esac
