#!/bin/bash

# display help
function help() {
  case $1 in
    reset)
      echo "reset containers"
      ;;
    *)
      echo "  $RUNNAME reset"
      ;;
  esac
}

# reset data
function reset() {
  confirm "Delete all data and reset all containers?" && containers development down -v
}

# run something
case "$1" in
  help) help "${@:2}";;
  reset) reset "${@:2}";;
esac
