#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    serve)
      echo "serve a production environment"
      ;;
    *)
      echo "  $RUNNAME serve"
      ;;
  esac
}

# run something
case $1 in
  help) help ${@:2};;
  serve) serve ${@:2};;
esac
