#!/bin/bash

#bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  case "$action" in
    help)
      echo up-help
      ;;
    sql) 
      compgen -W "$(containers development config --services)" -- "$subact"
      ;;
  esac
}

# display help
function help() {
  case $1 in
    sql)
      echo "sql console for dev environment"
      ;;
    *)
      echo "  $RUNNAME sql"
      ;;
  esac
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  sql) dockerexec postgres bash -c pg_psql "${@:2}";;
esac
