#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    sql)
      echo "sql console for dev environment"
      ;;
    *)
      echo "  $RUNNAME sql"
      ;;
  esac
}

# run something
case "$1" in
  help) help "${@:2}";;
  sql) runexec -it postgres pg_psql "${@:2}";;
esac
