#!/bin/bash

# bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

 [ "$action" = up ] && compgen -W "$(containers development config --services)" -- "$subact"
}

# display help
function help() {
  case $1 in
    up)
      echo "start a local dev environment"
      ;;
    *)
      echo "  $RUNNAME up"
      ;;
  esac
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  up) containers development up -d "${@:2}";;
esac
