#!/usr/bin/env bash

# bash completion
function completion() {
  local action="$1"
  local subact=( "${@:2}" )

  if [ "$action" = up ]; then
    compgen -W "$(runcompose config --services)" -- "$subact"
  fi
}

# display help
function help() {
  case $1 in
    up)
      echo "start a local dev environment"
      ;;
    *)
      echo "  $RUNNAME up"
      ;;
  esac
}

# docker up
function up() {
  local success
  local services="$@"

  [ -z "${services}" ] && services='${DEPLOY_SERVICES//,/ }'

  runcompose up -d "$services"

  success=$?

  [ "$success" != 0 ] && echo "Errors encoutered." && return

  [ -n "$1" ] && return

  echo ""
  echo "  Runcore is up. Next try:"
  echo ""
  echo "  $RUNNAME website"
  echo "  $RUNNAME mobile"
  echo "  $RUNNAME desktop"
  echo "  $RUNNAME console"
  echo "  $RUNNAME sql"
  echo ""
}

# run something
case "$1" in
  $'\t') completion "${@:2}";;
  help) help "${@:2}";;
  up) up "${@:2}";;
esac
