#!/usr/bin/env bash

# display help
function help() {
  case $1 in
    website)
      echo "launch website"
      ;;
    *)
      echo "  $RUNNAME website"
      ;;
  esac
}

# display website
function website() {
  isupordie caddy

  xdg-open "http://$(setting domain.name)/"
}

# run something
case $1 in
  help) help ${@:2};;
  website) website ${@:2};;
esac
