#!/usr/bin/env bash

set -Eeuo pipefail

# use the original docker entry file
source /usr/local/bin/docker-entrypoint.sh

# fix arguments if needed 
if [ "$#" -eq 0 ] || [ "$1" != 'postgres' ]; then
	set -- postgres "$@"
fi

# setup base environment
docker_setup_env

# setup data directories and permissions (when run as root)
docker_create_db_directories

if [ "$(id -u)" = '0' ]; then
	# then restart script as postgres user
	exec gosu postgres "$BASH_SOURCE" "$@"
fi

# only run initialization on an empty data directory
if [ -z "$DATABASE_ALREADY_EXISTS" ]; then
	docker_verify_minimum_env
	docker_init_database_dir
	pg_setup_hba_conf "$@"

	cat <<-'EOM'
		Data directory created and setup
	EOM
else
	cat <<-'EOM'
		Data directory initialized
	EOM
fi

# PGPASSWORD is required for psql when authentication is required for 'local' connections via pg_hba.conf and is otherwise harmless
# e.g. when '--auth=md5' or '--auth-local=md5' is used in POSTGRES_INITDB_ARGS
export PGPASSWORD="${PGPASSWORD:-$POSTGRES_PASSWORD}"

# Start temp server
docker_temp_server_start "$@"

# Setup database
docker_setup_db

# Create database from initfiles
pg_initdb

# Load data from datafiles
pg_dataload

# Stop temp server
docker_temp_server_stop

unset PGPASSWORD

# Run main server
exec "$@"
