#!/usr/bin/env bash

# ensure the script is run as the postgres user
if [ "$(id -u)" = '0' ]; then
  exec gosu postgres "$BASH_SOURCE" "$@"
fi

# return table order from postgres
echo "
  SELECT *
  FROM table_insert_order();
" | PGHOST= PGHOSTADDR= psql -v QUIET=1 ON_ERROR_STOP=1 --username "$POSTGRES_USER" --no-password --no-psqlrc --dbname "$POSTGRES_DB" -t -A
