table:
  name: settings
  schema: core
object_relationships:
  - name: from
    using:
      foreign_key_constraint_on: feature
array_relationships:
  - name: derivations
    using:
      foreign_key_constraint_on:
        column: setting
        table:
          name: settings
          schema: main
