table:
  name: configs
  schema: main
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
  - name: form
    using:
      foreign_key_constraint_on: form_name
