table:
  name: settings
  schema: main
object_relationships:
  - name: account
    using:
      foreign_key_constraint_on: account_id
  - name: origin
    using:
      foreign_key_constraint_on: setting
