#!/bin/bash

#bash completion
function completion() {
  COMP_WORDS=(docker compose "${COMP_WORDS[@]:2}")
  COMP_CWORD=$((COMP_CWORD + 1))
  _docker
  return
}

# display help
function help() {
  case $1 in
    up)
      echo "start a local dev environment"
      ;;
    *)
      echo "  $RUNNAME up"
      ;;
  esac
}

# run something
case $1 in
  help) help ${@:2};;
  up) up ${@:2};;
esac
