table:
  name: settings
  schema: setup
array_relationships:
  - name: inherited_by
    using:
      foreign_key_constraint_on:
        column: setting_id
        table:
          name: settings
          schema: client
